"""add history summary to sessions

Revision ID: 3037d56ebb1c
Revises: e7c9edfbe0c6
Create Date: 2026-07-21 08:33:05.471757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3037d56ebb1c'
down_revision: Union[str, Sequence[str], None] = 'e7c9edfbe0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('history_summary', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('unsummarized_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'unsummarized_count')
    op.drop_column('sessions', 'history_summary')
    # ### end Alembic commands ###
